#pragma kernel CSMain
#include "/Density.compute"

float density(float3 pos)
{
    pos /= octaves[0].x;
    return pos.x*pos.x*pos.x-pos.y*pos.y+pos.z*pos.z;
}

[numthreads(8,8,8)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if(id.x >= ppa || id.y >= ppa || id.z >= ppa)
        return;
    
    float3 pos = id*sampleInterval + offset;
    pts[coordToIndex(id.x, id.y, id.z)] = float4(pos-offset, density(pos));
}
